// DECK TYPE ACTIONS
export const ADD_DECK_SUCCESS = 'ADD_DECK_SUCCESS';
export const ADD_DECK_FETCHING = 'ADD_DECK_FETCHING';
export const ADD_DECK_FAIL = 'ADD_DECK_FAIL';
export const GET_DECKS_FETCHING = 'GET_DECKS_FETCHING';
export const GET_DECKS_SUCCESS = 'GET_DECKS_SUCCESS';
export const GET_DECKS_FAIL = 'GET_DECKS_FAIL';


// CARD TYPE ACTIONS
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FETCHING = 'ADD_CARD_FETCHING';
export const ADD_CARD_FAIL = 'ADD_CARD_FAIL';
export const GET_CARDS_FETCHING = 'GET_CARDS_FETCHING';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_FAIL = 'GET_CARDS_FAIL';